extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - deprecation
rules:
  deprecation/deprecation: error
env:
  node: true
